In [1]:
from __future__ import division
import numpy as np
from scipy import linalg as la

In [61]:
from numba import jit

In [104]:
@jit
def jacobi_method(A, b, maxiters=10000, tol=0.0001):
    n = A.shape[0]
    x0 = np.zeros(n)
    x1 = np.ones(n)
    k = 0
    while np.max(np.abs(x0-x1)) > tol:
        k += 1
        temp = np.copy(x1)
        for i in xrange(n):
            s = 0
            for j in xrange(n):
                if j != i:
                    s += A[i,j]*x0[j]
            x1[i] = (b[i] - s)/A[i,i]
        x0 = temp
        if k > maxiters:
            print("Hit maxiters!")
            return x1
    print(k)
    return x1

In [3]:
A = np.random.random_integers(-9,9,9).astype(float).reshape(3,3)
np.fill_diagonal(A,5*np.diag(A))
A //= 10

array([[-7.,  0., -1.],
       [-1., -4., -1.],
       [ 0., -1., -4.]])

In [24]:
b = np.random.random_integers(-9,9,3).astype(float)

In [115]:
%time la.inv(B).dot(c)

CPU times: user 4 ms, sys: 12 ms, total: 16 ms
Wall time: 5.11 ms


array([-1.0471303 ,  0.98036419,  0.19016231,  0.17989796, -0.54289434,
       -1.16946016, -0.18770944,  1.04127559, -0.90655208,  1.42893666,
       -1.40931827, -0.22341695, -1.06068466,  0.79234774, -0.90231416,
        0.86886328, -0.87529529,  0.20475056,  2.52916415, -0.55695449,
       -0.58969905, -0.41646234,  1.54099098,  1.92910538,  1.17368709,
       -0.34288519, -1.68396665, -0.10465555, -0.18544163, -0.22548657,
        0.44476016, -0.61326861, -0.181383  ,  1.23039573,  1.47474508,
       -1.52495166, -0.57822291, -0.57675757, -0.68857167, -2.66375051,
       -0.12198918, -0.35029377, -0.7834366 ,  0.55521765, -2.00992383,
        0.06126542, -2.58215602,  0.37255092, -0.19928386, -2.03533067,
        2.98216862, -1.62274317, -1.04713667, -1.01511988, -1.43480878,
        0.79294091, -0.19998745,  1.34905848, -2.00590757,  0.54021791,
       -1.93866089,  0.41339508, -0.6394065 ,  0.15750098, -0.00921421,
       -0.15865276,  0.72897337,  0.89206674,  1.14986265, -0.49

In [117]:
%time jacobi_method(B,c,tol=0.1)

2272

CPU times: user 7.53 s, sys: 12 ms, total: 7.54 s
Wall time: 7.43 s


/home/tanner/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in double_scalars
  if __name__ == '__main__':
/home/tanner/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan])

In [103]:
%prun jacobi_method(B,c)

18

 

In [111]:
B = np.random.random_integers(-9,9,10000).astype(float).reshape(100,100)
B //= 5
np.fill_diagonal(B,10*np.diag(B))
np.fill_diagonal(B,np.diag(B)+5)

In [112]:
c = np.random.random_integers(-9,9,100).astype(float)

In [120]:
np.sum(B)

-4165.0