In [12]:
import numpy as np
from scipy import linalg as la
from matplotlib import pyplot as plt
from matplotlib import cm

In [5]:
#Problem 1 
def problem1(A, k):
    # A - np.array of size m x n
    # k - integer
    U,s,Vt = la.svd(A, full_matrices=False)
    #print U
    #print s
    #print Vt
    if (k >= len(s)):
        #pass
        print "do something special here" 
    else:
        difference = len(s) - k
        U = U[:,:-difference]
        S = np.diag(s[:-difference])
        Vt = Vt[:-(difference),:]
        #print (U.nbytes + S.nbytes + Vt.nbytes) - A.nbytes
        A_hat = U.dot(S).dot(Vt)
        #print la.norm(A - A_hat, ord=2)
        return A_hat
    

In [15]:
#Problem 2
def problem2(A, e):
    '''
    U,s,Vt = la.svd(A, full_matrices=False)
    S = np.diag(s)
    i = 1
    if s[-1] > e:
        best = len(s) - 1
    else: 
        while s[-i] < e:
            if s[-(i+1)] < e:
                i += 1
            elif s[-(i+1)] > e:
                best = len(s) - i
                break
    n = best
    u1, s1, vt1 = U[:,0:n], S[0:n,0:n], Vt[0:n,:]
    print (u1.nbytes + np.diag(s1).nbytes + vt1.nbytes) - A.nbytes
    return u1.dot(s1).dot(vt1) 
    '''
    U,s,Vt = svd(A, full_matrices=False)
    k = np.where(s<e)[0][0]
    S = np.diag(s[:k])
    return U[:,:k].dot(S).dot(Vt[:k,:])

In [10]:
A = np.array([[1,1,3,4], [5,4,3,7], [9,10,10,12], [13,14,15,16],
[17,18,19,20]])

In [45]:
img_red.shape

(400, 388)

In [44]:
%timeit img_red_compressed = problem2(img_red, 5)

33
33
33
33
1 loops, best of 3: 603 ms per loop


In [19]:
plt.imshow(img_red)

array([[  0.9427572 ,   1.06132868,   2.97751578,   4.01390747],
       [  4.91861722,   4.08719173,   2.96803391,   7.01977242],
       [  9.29704956,   9.68174761,  10.11667717,  11.92783009],
       [ 12.99779036,  14.00236736,  14.99913208,  16.00053685],
       [ 16.8648845 ,  18.14475978,  18.94692841,  20.03282709]])

In [13]:
U1 = U[:,0]
Vt1H = (Vt[:,0]).T

In [10]:
U.shape


(5, 4)

In [20]:
from matplotlib import pyplot as plt


In [21]:
img_red = plt.imread("hubble_image.jpg")[:,:,0].astype(float)

In [22]:
img_red


array([[ 77.,  83.,  87., ...,  56.,  61.,  64.],
       [ 81.,  84.,  87., ...,  53.,  57.,  60.],
       [ 86.,  86.,  86., ...,  52.,  55.,  58.],
       ..., 
       [ 38.,  20.,  29., ...,  57.,  60.,  63.],
       [ 18.,  18.,  27., ...,  57.,  58.,  59.],
       [ 13.,  23.,  24., ...,  58.,  56.,  54.]])

In [23]:
plt.imshow(img_red)
plt.show()

In [40]:
%timeit U,s,Vt = la.svd(img_red,full_matrices=False)

1 loops, best of 3: 496 ms per loop


In [25]:
n = 50
u1, s1, vt1 = U[:,0:n], S[0:n,0:n], Vt[0:n,:]
img_compressed = u1.dot(s1).dot(vt1)

In [27]:
(u1.nbytes + np.diag(s1).nbytes + vt1.nbytes) - img_red.nbytes

-926000

In [32]:
np.where?


In [150]:
U,s,Vt = la.svd(img_red, full_matrices=False)

In [158]:
np.where(s<50)[0][0]
print s[260]

49.0292608929


In [36]:
e = 5
i = 1
if s[-1] > e:
    best = len(s) - 1
else: 
    while s[-i] < e:
        if s[-(i+1)] < e:
            i += 1
        elif s[-(i+1)] > e:
            best = len(s) - i
            print i
            break

33


In [113]:
plt.subplot(2, 1, 1)
plt.imshow(img_red)
plt.subplot(2,1,2)
plt.imshow(problem2(img_red, 200))
plt.show()


-269552


In [17]:
img_red = plt.imread("hubble_image.jpg")[:,:,0].astype(float)
img_green = plt.imread("hubble_image.jpg")[:,:,1].astype(float)
img_blue = plt.imread("hubble_image.jpg")[:,:,2].astype(float)

original_img = plt.imread("hubble_image.jpg").astype(float)

e = 200

adjust = np.zeros(original_img.shape) + 256

img = np.copy(original_img)
img[:,:,0] = problem2(img_red, e)
img[:,:,1] = problem2(img_green, e)
img[:,:,2] = problem2(img_blue, e)



img = np.array(img).astype(int)

plt.subplot(1,2,1)
plt.imshow(adjust - original_img)

plt.subplot(1,2,2)
plt.imshow(adjust - img)

print norm(original_img - img)

plt.show()

2289.50409478


In [166]:
plt.imshow(img[330:370,50:100,:])
plt.show()

In [112]:
plt.imshow(img, cmap='hot_r')
plt.show()

In [100]:
plt.imshow(img)
plt.savefig("output.jpg")

In [77]:
colormap_r = matplotlib.colors.ListedColormap(matplotlib.cm.colors[::-1])

TypeError: 'module' object has no attribute '__getitem__'

In [79]:
matplotlib.cm.h

In [81]:
plt.imshow?

In [132]:
plt.imshow(problem1(img_red, 100))
plt.show()

-531200


In [127]:
plt.show()

In [126]:
plt.set_cmap('gray')

In [201]:
np.where(img[330:370,50:100,:]==0)

(array([ 1,  2,  2,  2,  2,  4,  4,  4,  6,  6,  6,  6,  6,  6,  7,  7,  7,
         7,  7,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 11, 11, 11, 11,
        12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 15,
        15, 15, 15, 15, 15, 15, 15, 16, 17, 17, 18, 18, 18, 18, 19, 19, 20,
        20, 20, 21, 21, 21, 21, 22, 23, 24, 29, 30, 31, 38, 39]),
 array([13, 11, 12, 20, 21,  2,  2, 30,  9, 11, 12, 19, 36, 46,  5, 24, 27,
        38, 48, 34, 37, 49,  8, 16, 22, 28, 33, 35, 40, 33, 24, 33, 34, 38,
         5, 12, 24, 26, 27, 29, 33, 38, 39, 27, 28, 31, 45, 29, 30, 33, 24,
        25, 26, 30, 32, 36, 37, 40, 40, 34, 40, 26, 27, 32, 34, 27, 35, 21,
        27, 32, 15, 18, 30, 31, 13,  2, 22,  3, 17, 33,  6,  0]),
 array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 

In [196]:
a = np.where(img>255)
counter = 0
for i in xrange(len(a[0])):
    if img[a[0][i], a[1][i], a[2][i]] > 255:
        counter += 1
        img[a[0][i], a[1][i], a[2][i]] = 255
print counter

459


In [194]:
len(a[0])

459

In [198]:
plt.imshow(img)

In [199]:
plt.show()

In [14]:
plt.imshow(problem2(img_red,200), cmap=cm.gray)
plt.show()

-269552


In [7]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import scipy.linalg as la
from scipy.linalg import svd, norm

def svd_approx(A, k):
    '''
    Calculate the best rank k approximation to A with respect to the induced
    2-norm. Use the SVD.
    Inputs:
        A -- array of shape (m,n)
        k -- positive integer
    Returns:
        Ahat -- best rank k approximation to A obtained via the SVD
    '''
    #compute the reduced SVD
    U,s,Vh = svd(A,full_matrices=False)
    
    #keep only the first k singular values
    S = np.diag(s[:k])
    
    #reconstruct the best rank k approximation
    return U[:,:k].dot(S).dot(Vt[:k,:])
    
    
def lowest_rank_approx(A,e):
    '''
    Calculate the lowest rank approximation to A that has error stricly less than e.
    Inputs:
        A -- array of shape (m,n)
        e -- positive floating point number
    Returns:
        Ahat -- the best rank s approximation of A constrained to have error less than e, 
                where s is as small as possible.
    '''
    #calculate the reduced SVD
    U,s,Vh = svd(A,full_matrices=False)
    
    #find the index of the first singular value less than e
    k = np.where(s<e)[0][0] 
    
    #now recreate the rank k approximation
    S = np.diag(s[:k])
    return U[:,:k].dot(S).dot(Vt[:k,:])
    

def readimg(filename, channel=None):
    if channel is not None:
        return sp.misc.imread(filename)[:,:,channel]
    else:
        return sp.misc.imread(filename)


def compressSVD(filename, rank, random=False, channel=None):
    img = plt.imread(filename)

    try:
        isize = img[:,:,0].shape
        colors = [la.svd(img[:,:,i]) for i in range(3)]
    except IndexError:
        isize = img.shape
        plt.gray()
        colors = la.svd(img)

    plt.ion()
    imgc = plt.imshow(img)
    newimg = sp.zeros_like(img)

    rank = range(1,rank+1)

    if random is True:
        sp.random.shuffle(rank)

    for r in rank:
        col_res = hat(colors, r-1, r)
        try:
            #col_res[0] = sp.where(col_res[0]>255, col_res[0], 255)
            #col_res[1] = sp.where(col_res[1]>255, col_res[1], 255)
            #col_res[2] = sp.where(col_res[2]>255, col_res[2], 255)

            #col_res[0] = sp.where(col_res[0]<0, col_res[0], 0)
            #col_res[1] = sp.where(col_res[1]<0, col_res[1], 0)
            #col_res[2] = sp.where(col_res[2]<0, col_res[2], 0)
            
            newimg[:,:,0] += col_res[0]
            newimg[:,:,1] += col_res[1]
            newimg[:,:,2] += col_res[2]

            ## for ch in range(3):
            ##     newimg[newimg[:,:,ch]<1]=0
            ##     newimg[newimg[:,:,ch]>254]=255
                
        except IndexError:
            newimg += col_res[0]
            ## newimg[newimg<1]=0
            ## newimg[newimg>254]=255
        
        imgc.set_data(newimg)
        plt.draw()
    plt.ioff()
    plt.show()

    return newimg


def hat(color_svd, lrank, urank):
    results = []
    if len(color_svd) == 3:
        r = 3
    else:
        r = 1
        
    for c in range(r):
        U = color_svd[c][0]
        S = sp.diag(color_svd[c][1])
        Vt = color_svd[c][2]
        results.append(U[:,lrank:urank].dot(S[lrank:urank, lrank:urank]).dot(Vt[lrank:urank,:]))
        
    return results
    
def matrix_rank(X):
    """Compute the rank of a matrix using the SVD"""
    
    S = la.svd(X, compute_uv=False)
    tol = S.max()*sp.finfo(S.dtype).eps
    return sum(S>tol)


In [8]:
compressed_img = compressSVD("hubble_image.jpg", 100)

IOError: [Errno 2] No such file or directory: 'hubble_image.jpg'