In [1]:
import numpy as np

def problem1(training_set, scaling_vector):
    output = np.copy(training_set)
    output = output/scaling_vector
    return output


#  This function is written assuming that the training set = [vectors[], labels] 
#       the vector at vectors[i] corresponds to labels[i]

def problem2(training_set, scaling_vector, unlabelled_vector):
    if type(training_set[0][0][0]) != float:
        print "you need floats in your training set"
    
    if type(unlabelled_vector[0]) != float:
        print "you need floats in your unlabelled vector"
    
    vectors = training_set[0]
    labels = training_set[1]
    
    scaled_data = problem1(vectors, scaling_vector)
    scaled_unlabelled_vector = problem1(unlabelled_vector, scaling_vector)
    nearest_neighbor_index = 0 
    nearest_distance = distance(scaled_data[0], scaled_unlabelled_vector)
    for i in xrange(len(scaled_data)):
        dist = distance(scaled_data[i], scaled_unlabelled_vector)
        if dist < nearest_distance:
            nearest_distance = dist
            nearest_neighbor_index = i
    print nearest_neighbor_index
    return labels[nearest_neighbor_index]
        
def distance(v1, v2):
    total = 0
    if (len(v1) != len(v2)):
        print "you're an idiot. Use your own function correctly"
    for i in xrange(len(v1)):
        total += (v1[i] - v2[i])**2
    return np.sqrt(total)

#1:15 for problems 1 and 2


def problem3():
    from sklearn import datasets as ds
    ds.load_iris()
    
    # This set of data has 150 instances (50 of each of three classes)
    # The data is formatted as:
    # [sepal length in cm,
    #  sepal width in cm,
    #  petal length in cm,
    #  petal width in cm]
    #
    # We are also told what the minimums, maximums, mean, SD, and class correlation
    # of each of these pieces of data are.

#problem 1-3: 1:40

def problem4_2(x):
    # x is an integer between 0-9
    labels, points, testlabels, testpoints = np.load('C:/Users/Tanner/Desktop/Work/PostalData.npz').items()
    labels = labels[1]
    points = points[1]
    count = 0.0
    total = 0
    for i in xrange(len(labels)):
        if labels[i] == x:
            total += points[i]
            count += 1
    print count
    return total/count

from sklearn import neighbors
def problem4_3(_points, _labels, _n, _w, _p):
    nbrsClassifier = neighbors.KNeighborsClassifier(n_neighbors = _n, weights = _w, p = _p)
    nbrsClassifier.fit(_points, _labels)
    return nbrsClassifier

def problem4_4(classifier, testpoints, testlabels):
    nbrs = classifier
    mylist = nbrs.predict(testpoints) == testlabels
    incorrect = []
    for i in xrange(len(mylist)):
        if mylist[i] == False:
            incorrect.append(i)
    return float(len(incorrect))/len(testlabels)

nbrs1 = problem4_3(points[1], labels[1], 4, "uniform", 2)
print problem4_4(nbrs1, testpoints[1], testlabels[1])

nbrs2 = problem4_3(points[1], labels[1], 10, "distance", 2)
print problem4_4(nbrs2, testpoints[1], testlabels[1])

nbrs3 = problem4_3(points[1], labels[1], 1, "distance", 2)
print problem4_4(nbrs3, testpoints[1], testlabels[1])

nbrs4 = problem4_3(points[1], labels[1], 1, "uniform", 2)
print problem4_4(nbrs4, testpoints[1], testlabels[1])

#3:30 total
# to visualize a given image, use plt.imshow(IMG.reshape(28,28))

NameError: name 'points' is not defined

In [2]:
problem4_2(1)

IOError: [Errno 2] No such file or directory: 'C:/Users/Tanner/Desktop/Work/PostalData.npz'

In [3]:
from matplotlib import pyplot as plt

In [4]:
import numpy as np

In [9]:
theta = np.linspace(0, 2*np.pi - 2*np.pi/9, 9)

In [6]:
len(theta)

9

In [36]:
P_perm = np.copy(P1)

In [39]:
P1 = np.array([[103,68],[87,109],[49,132],[6,127],[-18,47],[-26,90],[5,11],[49,3],[87,26]])

In [77]:
P1[2] = [49,132]

In [29]:
from scipy import linalg as la

In [99]:
A = np.hstack((2*P1, np.ones((9,1))))
b = (P1**2).sum(axis=1)
c1, c2, c3 = la.lstsq(A, b)[0]
r = np.sqrt(c1**2 + c2**2 + c3)
theta = np.linspace(0,2*np.pi,200)
plt.plot(r*np.cos(theta)+c1,r*np.sin(theta)+c2,'-',P1[:,0],P1[:,1],'*')
plt.axes().set_aspect('equal', 'datalim')
plt.show()

In [91]:
for i in P1:
    list(P1[0])


In [80]:
temp = P1[0]
P1[0] = P1[6]
P1[6] = temp

In [83]:
len(P1)

9

In [87]:
temp

array([ 5, 11])

In [88]:
P1[6] = [103,68]

In [95]:
np.array(P1)

array([[  5,  11],
       [ 93, 110],
       [ 49, 132],
       [  4, 128],
       [-23,  47],
       [-26,  92],
       [103,  68],
       [ 48,   0],
       [ 86,  21]])

In [97]:
print np.min(P1,axis=0)
print np.max(P1,axis=1)
print np.min(P1,axis=0)
print np.max(P1,axis=1)

[-26   0]
[ 11 110 132 128  47  92 103  48  86]
[-26   0]
[ 11 110 132 128  47  92 103  48  86]


In [ ]:
#min_x = -26
#min_y = 0
#max_x = 103
#max_y = 132