In [12]:
def MGS(A):
    m, n = A.shape
    Q = np.copy(A)
    R = np.zeros((n,n))
    for i in range(0,n):
        R[i,i] = la.norm(Q[:,i])
        Q[:,i] = Q[:,i]/la.norm(Q[:,i])
        for j in range(i+1,n):
            R[i,j] = np.dot(Q[:,j], Q[:,i])
            #Q[:,j] = Q[:,j] - np.dot(Q[:,j], Q[:,i])*Q[:,i]
            for k in range(0,m):
                Q[k,j] = Q[k,j] - np.dot(Q[k,j], Q[k,i])*Q[k,i]
    return Q,R

In [3]:
def MGS_opt(A):
    norm = np.linalg.norm
    m, n = A.shape
    Q = np.copy(A)
    R = np.zeros((n,n))
    for i in xrange(0,n):
        R[i,i] = norm(Q[:,i])
        Q[:,i] = Q[:,i]/R[i,i]
        for j in xrange(i+1,n):
            R[i,j] = np.dot(Q[:,j], Q[:,i])
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
    return Q,R

In [4]:
import numpy as np
from scipy import linalg as la

In [29]:
n = 300
A = np.random.random_integers(-9,9,n**2).reshape((n,n))

In [21]:
np.allclose(MGS(A),MGS_opt(A))

True

In [30]:
%time MGS(A)

CPU times: user 21.3 s, sys: 4 ms, total: 21.3 s
Wall time: 21.3 s


(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[ 92.1249152 ,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        ,  95.24179755,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        ,  99.21189445, ...,   0.        ,
           0.        ,   0.        ],
        ..., 
        [  0.        ,   0.        ,   0.        , ...,  94.58329662,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        , ...,   0.        ,
          99.483667  ,   0.        ],
        [  0.        ,   0.        ,   0.        , ...,   0.        ,
           0.        ,  95.05261701]]))

In [31]:
%time MGS_opt(A)

CPU times: user 280 ms, sys: 4 ms, total: 284 ms
Wall time: 283 ms


(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[ 92.1249152 ,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        ,  95.24179755,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        ,  99.21189445, ...,   0.        ,
           0.        ,   0.        ],
        ..., 
        [  0.        ,   0.        ,   0.        , ...,  94.58329662,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        , ...,   0.        ,
          99.483667  ,   0.        ],
        [  0.        ,   0.        ,   0.        , ...,   0.        ,
           0.        ,  95.05261701]]))